server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /api
management:  
  port: 9090
  health: 
    db:
      enabled: true  
spring:
  dubbo:
    application.name: consumer
    registry.address: zookeeper://127.0.0.1:2181
    scan: com.sawyer.springboot
logging: 
    config: classpath:logback.xml
    path: D:/logs/springboot/
    level:
        root: debug
        org.apache.zookeeper: error
        com.alibaba.dubbo: info
        